server.port=8083
spring.application.name=hotel-api-gateway-service

spring.cloud.gateway.routes[0].id=users
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URI:http://localhost:8080}
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=PrefixPath=/api

spring.cloud.gateway.routes[1].id=notifications
spring.cloud.gateway.routes[1].uri=${NOTIFICATION_SERVICE_URI:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].filters[1]=PrefixPath=/api

spring.cloud.gateway.routes[2].id=reservations
spring.cloud.gateway.routes[2].uri=${RESERVATION_SERVICE_URI:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/reservations/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[2].filters[1]=PrefixPath=/api

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,PATCH,HEAD,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.preferIpAddress=true
