server.port=8080
server.servlet.context-path=/api
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
oauth.jwt.secret=VZ1OPVeDyVxBo0lh6W2zfTswUOROTuB/f5Sx3xW1GWPyXffb83AeQ99R20dRhhgyI4KmkMATu+uAp4eXPuylJg==
spring.application.name=hotel-user-service
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.preferIpAddress=true

amq.url=${AMQ_URL:tcp://localhost:61616}
amq.queryParameters=?jms.prefetchPolicy.all=1&jms.redeliveryPolicy.maximumRedeliveries=0
spring.activemq.broker-url=${amq.url}${amq.queryParameters}
destination.message=user_message
